### ISSUE TITLE
Is the Showcase still being updated?

### ISSUE THREAD

**Issue by anaurelian** [netlify/dusty-domains#63]
Over the last few days, I have submitted two pages to [Dusty Domains](https://dusty.domains/), and because of this I periodically refreshed the site. So I noticed that the Showcase did not change (no new pages were added).

**Comment by tools-netlify** [comment]
Hi @anaurelian! We're a little light on team members with the holiday season but I'll look into updating it today 👍

**Comment by jlengstorf** [comment]
hey! we got it sorted out — sites should be posted now!
