### ISSUE TITLE
One duplicate in the Showcase

### ISSUE THREAD

**Issue by anaurelian** [netlify/dusty-domains#64]
I guess it's a really minor detail, but here it is:

https://new-year-counter-2022.netlify.app/ appears twice in the list

Double-checked with

```js
[...document.querySelectorAll('.sites-item a')].map(e => e.href).filter((s => v => s.has(v) || !s.add(v))(new Set))
```

**Comment by lynnandtonic** [comment]
I think this should be fixed now. Thank you!!
